### PR TITLE
Banner and logo added to dashboard

### LINKED ISSUE #33: Create Website Header
image

Create a basic header for the website. There isn't any need for interactivity. Get the logo from the design.

### PR DESCRIPTION
**Pull request by LiamB94**
Added banner implemtation to dashboard and a png of the logo
closes #33 and #86

### CODE REVIEW

**Comment by vonner04** [comment]
Lgtm. I think to resolve the merge conflicts for Dashboard.jsx you can just add both imports from banner-implementation and main. I'm not too sure with the package-lock.json file.

**Review by vonner04 — CHANGES_REQUESTED** [review]
I think to resolve the merge conflicts for Dashboard.jsx you can just add both imports from banner-implementation and main. I'm not too sure with the package-lock.json file.

**Comment by clen678** [comment]
can you also pls remove the bg-blue from  <div className='bg-blue-500 flex items-center h-12 p-4'>?

**Comment by Taks07** [comment]
@vonner04 ive tried fixing the conflicts

**Review by vonner04 — APPROVED** [review]

**Pull request merged**
