### PR TITLE
Adding Savings Tracker and Setting Savings Goal components

### LINKED ISSUE #41: Create savings tracker
image

Create the savings tracker component. Adding a new savings goal depends on #40, but the basic component and progress bar can be made first

### LINKED ISSUE #81: Database Error: Column 'goal' Not Found in Users Table
**Describe the bug**
SQL/Database querying error of USERS table column saving_goal. 

**To Reproduce**
1. Use axios to fetch and update user's goal.

**Expected behavior**
Should update the saving_goal value cleanly without any errors.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by vonner04**
**Feature**

- Basic UI Layout for SavingsTracker and SetGoal component 
- SetGoal component as popup modal window when attempting to set a new savings goal
- Uses global tailwind config colors for red and blue.
- Added global css style to remove the up and down arrows for default style of input element, type = number 
- Rectangular Progress Bar dynamically updates and filled when balance/goal are altered. 
- Max savings goal is currently 1 million.

image

image

**Fixes**
- querying saving_goal instead of the non-existent goal column of users table

resolves #81 
resolves #41

### CODE REVIEW

**Review by clen678 — APPROVED** [review]
lgtm

**Review by clen678 — CHANGES_REQUESTED** [review]
actually looks like you have a conflict now

**Review by clen678 — APPROVED** [review]
lgtm

**Comment by vonner04** [comment]
> actually looks like you have a conflict now, would you be able to resolve this?
Yep. I just added what was on the main branch.

**Comment by vonner04** [comment]
Almost complete, just gonna refactor fetching balance via Context Provider. Once #84 is squash merged.

**Pull request merged**
