### PR TITLE
fixed error in DBtables syntax, and added new cert for new CloudDB

### PR DESCRIPTION
**Pull request by tom1dev**
fixes the issue where creating new tables for a DB throws a syntax error.
 
bug: https://github.com/Taks0708/SOFTENG310-FinTrack/issues/138

### CODE REVIEW

**Review by hsjhdko0 — APPROVED** [review]
looks good to me

**Comment by chrisv09** [comment]
looks good to me!

**Review by chrisv09 — APPROVED** [review]
Looks good to me!

**Review by chrisv09 — APPROVED** [review]
Looks good to me!

**Review by chrisv09 — APPROVED** [review]
Looks good to me!

**Review by Taks0708 — APPROVED** [review]
Looks good to me!

**Review by chrisv09 — APPROVED** [review]
I SAID it looks good ! :D

**Pull request merged**
